# Generated by Django 5.0.6 on 2024-07-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='category',
        ),
    ]
