# Generated by Django 5.0.6 on 2024-07-05 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_menyu_remove_producttype_category_delete_menu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('buyurtma_sanasi', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.menyu')),
            ],
        ),
    ]
